title: Your Website's Title
description: A brief description of your website.
baseurl: "postgrescontributors" # the subpath of your site, e.g. /blog
# baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com
